feat: dark mode
lcpu-club/mirror-frontend pull request #18
Opened 2023-03-20 10:22 UTC by Yixuan-Wang

Dark mode (experimental).

2023-03-21 07:58 UTC, thezzisu requested changes

2023-03-21 07:58 UTC, thezzisu commented on assets/images/mirror-text.svg
Now on light color schema the logo is gone😂

Restore the original mirror-text.svg (black). Use filter to invert the color on dark mode.

2023-03-25 03:22 UTC, Yixuan-Wang commented on assets/images/mirror-text.svg
Found a typo in `mirror-text.svg`. I wrote an `#fff` instead of `#000`🫠, so this solution should have worked without using filter.

2023-03-25 05:17 UTC, thezzisu approved these changes
Great work!

2023-03-25 05:17 UTC, merged